name: "Move the Issue after it has been assigned"

on:
  issues:
    types: [assigned]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      # Befor assigning someone to an issue, the workload and priority should be set
      - name: "Check if workload is set"
        id: check_workload
        if: |
          contains(join(github.event.issue.labels.*.name, ','), 'workload:high') ||
          contains(join(github.event.issue.labels.*.name, ','), 'workload:medium') ||
          contains(join(github.event.issue.labels.*.name, ','), 'workload:low')
        run: |
            echo "WORKLOAD_SET=true"
