name: "Move the Issue after workload and urgency is evaluated"

on:
  issues:
    types: [labeled]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if workload is set"
        id: check_workload
        # Check if the issue has a workload label
        if: |
          contains(join(github.event.issue.labels.*.name, ','), 'workload:high') ||
          contains(join(github.event.issue.labels.*.name, ','), 'workload:medium') ||
          contains(join(github.event.issue.labels.*.name, ','), 'workload:low')
        run: |
            echo "WORKLOAD_SET=true" >> $GITHUB_ENV
            # extract the workload value
            labels=$(echo '${{ toJSON(github.event.issue.labels) }}' | jq -r '.[].name')
            workload=$(echo "$labels" | grep -oE 'workload:(high|medium|low)' | cut -d: -f2)
            echo "WORKLOAD=$workload" >> $GITHUB_OUTPUT
      - name: "Check if priority is set"
        id: check_urgency
        # Check if the issue has a priority label
        if: |
          contains(join(github.event.issue.labels.*.name, ','), 'priority:high') ||
          contains(join(github.event.issue.labels.*.name, ','), 'priority:medium') ||
          contains(join(github.event.issue.labels.*.name, ','), 'priority:low')
        run: |
            echo "PRIORITY_SET=true" >> $GITHUB_ENV
            # extract the priority value
            labels=$(echo '${{ toJSON(github.event.issue.labels) }}' | jq -r '.[].name')
            priority=$(echo "$labels" | grep -oE 'priority:(high|medium|low)' | cut -d: -f2)
            echo "PRIORITY=$priority" >> $GITHUB_OUTPUT
      - name: "Find associated Projects"
        id: find_projects
        # Find the projects associated with the organization
        run: |
          projects=$(curl --request POST \
                            --url https://api.github.com/graphql \
                            --header "Authorization: Bearer ${{ secrets.TEST_SECRET }}" \
                            --data '{"query":"{organization(login: \"DLR-AMR\") {projectsV2(first: 20) {nodes {id title}}}}"}')
          echo "projects=$projects">> $GITHUB_OUTPUT
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with: 
          repository: ${{ github.event.repository.full_name }}
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
      - name: "Move issue to 'ToDo' column in associated projects"
        if: env.WORKLOAD_SET == 'true' && env.PRIORITY_SET == 'true'
        uses: ./.github/workflows/move_card.yml
        with: 
            ISSUE_NODE_ID: ${{ github.event.issue.node_id }}
            COLUMN_NAME: "ToDo"
            PRIORITY: ${{ steps.check_urgency.outputs.PRIORITY }}
            WORKLOAD: ${{ steps.check_workload.outputs.WORKLOAD }}
        
            