name: "Update the version of this repository"

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    branches:
      - main

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    outputs: 
      trigger_version_update: ${{ steps.check_commit_message.outputs.VERSION_UPDATE }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ secrets.TEST_SECRET }}
        fetch-depth: 0
    - name: Check commit message
      id: check_commit_message
      run: |
        if ! git diff --quiet HEAD~1 HEAD; then
          echo "The latest commit is not empty. Exiting."
          echo "Do not update version"
          echo "VERSION_UPDATE=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "message: $COMMIT_MESSAGE"
        if [[ "$COMMIT_MESSAGE" == "Update Version" ]]; then
          echo "Update version"
          echo "VERSION_UPDATE=true" >> $GITHUB_OUTPUT
          else
          echo "Do not update version"
          echo "VERSION_UPDATE=false" >> $GITHUB_OUTPUT
        fi
  
  update_version:
    if: (github.event_name == 'pull_request' && needs.check_commit_message.outputs.trigger_version_update == 'true')
    uses: ./.github/workflows/create_version_tag.yml
    secrets: inherit
    needs: [check_commit_message]